### ISSUE TITLE
Layout missing for Dinky Jekyll theme

### ISSUE THREAD

**Issue by tyhopp** [pages-themes/dinky#1]
Bug Name: Jekyll server can not find layout “post” when first using theme Dinky
Build Number: Jekyll 3.3.1; jekyll-theme-dinky 0.0.3
Severity: Low
Reported By: Ty Hopp
Reported On: 25 January 2017
Reason: Defect
Status: New
Environment: MacOS Sierra 10.12.2, Ruby 2.4

Description:
Jekyll server returns “Layout ‘post’...does not exist” when running [bundle exec jekyll serve] after installing the gem jekyll-theme-dinky for the first time. Jekyll docs states that _layouts dir is located away from project dir when using supported themes, but after visiting the path
 [ /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-theme-dinky-0.0.3/_layouts], only the “default.html" layout exists. Has the “post” layout gone missing?
<img width="644" alt="screen shot 2017-01-25 at 8 30 19 pm" src="https://cloud.githubusercontent.com/assets/13206278/22316341/824aca04-e3a7-11e6-86c1-c669ab135ca1.png">

Edit: After further digging, I found that another theme (Minimal) had the same problem. Only the Minima theme contains all the layouts.

<img width="603" alt="screen shot 2017-01-26 at 10 31 52 am" src="https://cloud.githubusercontent.com/assets/13206278/22318162/58f55212-e3b3-11e6-8663-70e6e8065340.png">
<img width="641" alt="screen shot 2017-01-26 at 10 33 32 am" src="https://cloud.githubusercontent.com/assets/13206278/22318164/5c575676-e3b3-11e6-9570-7f1f45cc82a4.png">
<img width="641" alt="screen shot 2017-01-26 at 10 34 14 am" src="https://cloud.githubusercontent.com/assets/13206278/22318165/5dd69d7c-e3b3-11e6-917b-5ba129298a23.png">

**Comment by tivaliy** [comment]
@tyhopp 
You can use default layout in your posts or create your own one in `_layouts`.

In my case I use:
---
layout: default
title:  blah-blah-blah

---
