### ISSUE TITLE
include script tag

### ISSUE THREAD

**Issue by deepcell** [pages-themes/dinky#11]
How to use ```<script>``` tag?

I couldn't find a clear example how to do that.

I have this includes to do:
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="/exchange-table.js"></script>

Is that possible?

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸

**Comment by deepcell** [comment]
It's not specific at all. I have a README.md file and want to provide some dynamic information in this file, and I just want to call jQuery and another .js script hosted at same level of README.md. But it seems that github pages does not allow to run javascript code with the markdown.
Also I couldn't find any answer about this issue.
Thanks anyway.

**Comment by deepcell** [comment]
That's how I did, it will parse.

```
<script src="{{ 'https://code.jquery.com/jquery-3.2.1.min.js' }}"></script>
<script src="{{ '/exchange-table.js' }}"></script>

```
